{% set name = "posthog" %}
{% set version = "3.16.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 953176a443b30b1404c0f36010a95caad60a83c31ecb17b427f6d986f6f765c1

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - requests >=2.7.0,<3.0.0
    - six >=1.5.0
    - monotonic >=1.5.0
    - backoff >=1.10.0
    - python-dateutil >=2.1.0
    - distro >=1.5.0

test:
  imports:
    - posthog
  requires:
    - freezegun =1.5.1
    - mock >=2.0.0
    - pip
    - pytest
    - pytest-timeout
    - pytest-asyncio
    - parameterized >=0.8.1
    - pydantic
  commands:
    - pip check
    - pytest --pyargs posthog.test -k "not test_basic_capture_exception_with_no_exception_given"

about:
  home: https://github.com/PostHog/posthog-python
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Integrate PostHog into any python application
  description: |
    Integrate PostHog into any python application
  dev_url: https://github.com/PostHog/posthog-python
  doc_url: https://posthog.com/docs/libraries/python


extra:
  recipe-maintainers:
    - Twixes
    - yakkomajuri
    - neilkakkar
    - posthog-bot
